[platformio]
default_envs = watchy_v3

[env:watchy_v3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
monitor_speed = 115200
lib_ldf_mode = deep+
extra_scripts =
  pre:${sysenv.PWD}/scripts/pio_ci_settings.py
build_flags =
  -DARDUINO_WATCHY_V30
  -DCORE_DEBUG_LEVEL=0
  ; Rtc_Pcf8563 master uses WireBase; ESP32 Arduino exposes TwoWire.
  -DWireBase=TwoWire
lib_deps =
  adafruit/Adafruit GFX Library
  arduino-libraries/Arduino_JSON
  jchristensen/DS3232RTC
  arduino-libraries/NTPClient
  paulstoffregen/Time
  https://github.com/orbitalair/Rtc_Pcf8563.git#master
  https://github.com/ZinggJM/GxEPD2.git#master
  https://github.com/tzapu/WiFiManager.git#master
